"""Added hashed_password to User model

Revision ID: 0a336d863725
Revises: 6c3f94fbac95
Create Date: 2024-09-30 23:26:58.649731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a336d863725'
down_revision: Union[str, None] = '6c3f94fbac95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=256), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'filename')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('filename', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.create_table('posts',
    sa.Column('postid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('owner_username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_username'], ['users.username'], name='posts_owner_username_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postid', name='posts_pkey')
    )
    # ### end Alembic commands ###
