"""Initial migration

Revision ID: 198e2cc566af
Revises: 
Create Date: 2024-09-30 22:50:12.231623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '198e2cc566af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('fullname', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('posts',
    sa.Column('postid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('owner_username', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
